### ISSUE TITLE
Large folder won't run

### ISSUE THREAD

**Issue by caca9512** [jabberjabberjabber/LLavaImageTagger#5]
a folder with 8000 images, indexer do nothing and show message "Image Indexer finished."

4000 images work.

**Comment by jabberjabberjabber** [comment]
When you open the .json file it makes in the directory what does it show?

**Comment by caca9512** [comment]
The json file was not generated

**Comment by jabberjabberjabber** [comment]
Works fine for me? 

![Capture](https://github.com/user-attachments/assets/128a812f-2173-4a52-888b-beae78d96d04)
