### ISSUE TITLE
Question: Software to Q&A a set of photos

### ISSUE THREAD

**Issue by peterchanws** [jabberjabberjabber/LLavaImageTagger#9]
I have added descriptions to a set of photos using your software. Is there a way to use an LLM to ask questions about the photos?

**Comment by peterchanws** [comment]
I want the LLM to use the already generated descriptions to answer the question about the photos.

**Comment by peterchanws** [comment]
The use case involves having thousands of photos with very brief metadata. I plan to use your program to generate descriptions and keywords for these photos, allowing users to ask questions about them.

**Comment by jabberjabberjabber** [comment]
Are these photos going to be changing at all, or are you planning to generate new captions after the first processing?

**Comment by jabberjabberjabber** [comment]
Sorry can you be specific about exactly what you want to do. Layout the entire process you plan and step me through it if you can.

**Comment by jabberjabberjabber** [comment]
Are you willing to join the Koboldcpp discord server so we can chat instead of using github issues, which are not suited for this?

**Comment by peterchanws** [comment]
Sure. Could I have in invite link?

**Comment by jabberjabberjabber** [comment]
https://discord.gg/DhupbxCP

**Comment by peterchanws** [comment]
I joined but don't have permission to post.

**Comment by peterchanws** [comment]
Posted.

**Comment by jabberjabberjabber** [comment]
Sorry I had to step out for a bit. I sent you a message.
